save

diff --git a/pipelines/steps/sdk-generation.yml b/pipelines/steps/sdk-generation.yml
--- a/pipelines/steps/sdk-generation.yml
+++ b/pipelines/steps/sdk-generation.yml
@@ -50,17 +50,17 @@ steps:
 
   - bash: |
       getTasksToRun
+      retVal=$?
+      if [ $retVal -ne 0 ]; then
+          echo -e "\033[0;31mGet tasks to run failed"
+          exit 1
+      fi
     displayName: Get Tasks To Run
     name: getTasksToRun
     workingDirectory: $(SDK_REPO)
     env:
       SDK_REPO: $(SDK_REPO)
       SKIPPED_STEPS: ${{ parameters.skippedTask }}
-
-  - template: after-task.yml
-    parameters:
-      sdkGenerationName: ${{ parameters.sdkGenerationName }}
-      taskName: getTasksToRun
 
   - bash: |
       if [[ $TASKS_TO_RUN == *"init"* ]]; then
