set exit code for task engine

diff --git a/.azure-pipelines/templates/GenerateCode.yml b/.azure-pipelines/templates/GenerateCode.yml
--- a/.azure-pipelines/templates/GenerateCode.yml
+++ b/.azure-pipelines/templates/GenerateCode.yml
@@ -29,6 +29,11 @@ steps:
     # $cmd $(ResourceProvider) $(Pipeline.Workspace)/s/azure-rest-api-specs "$(ResourceProvider)" $(Pipeline.Workspace)/s/azure-sdk-for-go>>$(Pipeline.Workspace)/s/$(TASK_KEY).log 2>&1
 
     cmd=`node dist/TaskEngine.js "$(CODEGEN_TO_SDK_CONFIG)" "GenerateCode" "$(SDK)" "$(ResourceProvider)" "$(Pipeline.Workspace)/s/azure-rest-api-specs/specification" "$(Pipeline.Workspace)/s/$(SDK_REPO_NAME)"`
+    if [ "$?" != "0" ]; then
+      echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: Not supported SDK"
+      echo "##vso[task.setvariable variable=Task_Result]failure"
+      exit 1
+    fi
     echo "cmd:$cmd"
     $cmd >>$(Pipeline.Workspace)/s/$(TASK_KEY).log 2>&1
     
